### ISSUE TITLE
Unable to install this package due to dependency issue

### ISSUE THREAD

**Issue by sptiwari** [rxn4chemistry/rxn-onmt-utils#8]
I encountered the following error while attempting to install the `rxn-onmt-utils` package:

```
ERROR: Cannot install rxn-onmt-utils because these package versions have conflicting dependencies.

The conflict is caused by:
    rxn-opennmt-py 1.1.5 depends on torch<1.6 and >=1.2
    rxn-opennmt-py 1.1.4 depends on torch<1.6 and >=1.2
    rxn-opennmt-py 1.1.3 depends on torch<1.6 and >=1.2
    rxn-opennmt-py 1.1.2 depends on torch<1.5 and >=1.2
    rxn-opennmt-py 1.1.1 depends on torch<1.4 and >=1.2
```

The installation failed due to conflicting version requirements for the `torch` dependency in the `rxn-opennmt-py` package. After disabling `rxn-opennmt-py`, I was able to successfully install `rxn-onmt-utils`. However, this appears to be a packaging issue with the dependencies specified for `rxn-opennmt-py`.

Could you please investigate and correct the dependency conflicts in the `pip` package? This will ensure that users can install it without having to disable packages manually.

**Comment by avaucher** [comment]
Hi,

The fork of OpenNMT used by this repository currently depends on versions of torch that are incompatible with torch 1.6 and higher. This limitation could cause installation issues, especially if you're using Python 3.9 or above, as there may not be pre-built versions of torch <1.6 for these Python versions.

As stated in the README:

> A Python version of 3.6, 3.7, or 3.8 is recommended. Python versions 3.9 and above are not expected to work due to compatibility with the selected version of OpenNMT.

Please feel free to share any additional errors you encounter during installation, and we'll be happy to assist further.

**Comment by avaucher** [comment]
Closing for now. Feel free to reopen the issue if needed.
